spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/calefit?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  #  sql:
  #    init:
  #  #      data-locations: classpath:data.sql
  #  #      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

oauth2:
  client:
    provider:
      kakao:
        client-id: ${KAKAO_CLIENT_ID}
        client-secret: ${KAKAO_CLIENT_SECRET}
        redirect-uri: http://localhost:8080/oauth/callback?providerType=kakao
        access-token-path: https://kauth.kakao.com/oauth/token
        resource-path: https://kapi.kakao.com/v2/user/me


      google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        redirect-uri: http://localhost:8080/oauth/callback?providerType=google
        access-token-path: https://www.googleapis.com/oauth2/v4/token
        resource-path: https://www.googleapis.com/oauth2/v3/userinfo

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}

logging:
  level:
    org.hibernate.SQL: debug


