oauth2:
  client:
    provider:
      kakao:
        client-id: ${KAKAO_CLIENT_ID}
        client-secret: ${KAKAO_CLIENT_SECRET}
        redirect-uri: http://localhost:8080/oauth/callback?providerType=kakao
        access-token-path: https://kauth.kakao.com/oauth/token
        resource-path: https://kapi.kakao.com/v2/user/me

      google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        redirect-uri: http://localhost:8080/oauth/callback?providerType=google
        access-token-path: https://www.googleapis.com/oauth2/v4/token
        resource-path: https://www.googleapis.com/oauth2/v3/userinfo
