spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3306/calefit?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}

logging:
  level:
    org.hibernate.SQL: debug

