name: CI

on:
  push:
    branches:
      - 'feature-**'
      - 'test-**'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci-test:
    name: SpringBoot Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: Use gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create mysql docker container
        run: |
          sudo docker run -d --name vans -p 3306:3306 --env MYSQL_DATABASE=calefit --env MYSQL_ROOT_PASSWORD=1234 mysql:8.0.23

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Docker check
        run: |
          docker ps
          while ! docker exec vans mysql --user=root --password=1234 -e "SELECT 1" >/dev/null 2>&1; do 
            sleep 2 
            echo "waiting for mysql.."
          done

      - name: Test with Gradle
        run: ./gradlew test --stacktrace
        
      - name: Noti Discord - CI test success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: CI test succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Noti Discord - CI test failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: CI test failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Noti Discord - CI test cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: Test Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
